/* pumpkin-application.c generated by valac 0.28.0, the Vala compiler
 * generated from pumpkin-application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define PUMPKIN_TYPE_APPLICATION (pumpkin_application_get_type ())
#define PUMPKIN_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PUMPKIN_TYPE_APPLICATION, PumpkinApplication))
#define PUMPKIN_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PUMPKIN_TYPE_APPLICATION, PumpkinApplicationClass))
#define PUMPKIN_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PUMPKIN_TYPE_APPLICATION))
#define PUMPKIN_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PUMPKIN_TYPE_APPLICATION))
#define PUMPKIN_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PUMPKIN_TYPE_APPLICATION, PumpkinApplicationClass))

typedef struct _PumpkinApplication PumpkinApplication;
typedef struct _PumpkinApplicationClass PumpkinApplicationClass;
typedef struct _PumpkinApplicationPrivate PumpkinApplicationPrivate;

#define PUMPKIN_TYPE_APPLICATION_WINDOW (pumpkin_application_window_get_type ())
#define PUMPKIN_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindow))
#define PUMPKIN_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindowClass))
#define PUMPKIN_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW))
#define PUMPKIN_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PUMPKIN_TYPE_APPLICATION_WINDOW))
#define PUMPKIN_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindowClass))

typedef struct _PumpkinApplicationWindow PumpkinApplicationWindow;
typedef struct _PumpkinApplicationWindowClass PumpkinApplicationWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _PumpkinApplication {
	GtkApplication parent_instance;
	PumpkinApplicationPrivate * priv;
	PumpkinApplicationWindow* window;
};

struct _PumpkinApplicationClass {
	GtkApplicationClass parent_class;
};


static gpointer pumpkin_application_parent_class = NULL;

GType pumpkin_application_get_type (void) G_GNUC_CONST;
GType pumpkin_application_window_get_type (void) G_GNUC_CONST;
enum  {
	PUMPKIN_APPLICATION_DUMMY_PROPERTY
};
PumpkinApplication* pumpkin_application_new (void);
PumpkinApplication* pumpkin_application_construct (GType object_type);
static void pumpkin_application_real_activate (GApplication* base);
PumpkinApplicationWindow* pumpkin_application_window_new (GtkApplication* application);
PumpkinApplicationWindow* pumpkin_application_window_construct (GType object_type, GtkApplication* application);
static void pumpkin_application_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint);
static void pumpkin_application_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


PumpkinApplication* pumpkin_application_construct (GType object_type) {
	PumpkinApplication * self = NULL;
#line 6 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	self = (PumpkinApplication*) g_object_new (object_type, NULL);
#line 7 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	g_application_set_application_id ((GApplication*) self, "net.dannote.pumpkin");
#line 6 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	return self;
#line 73 "pumpkin-application.c"
}


PumpkinApplication* pumpkin_application_new (void) {
#line 6 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	return pumpkin_application_construct (PUMPKIN_TYPE_APPLICATION);
#line 80 "pumpkin-application.c"
}


static void pumpkin_application_real_activate (GApplication* base) {
	PumpkinApplication * self;
	PumpkinApplicationWindow* _tmp0_ = NULL;
	PumpkinApplicationWindow* _tmp1_ = NULL;
#line 10 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	self = (PumpkinApplication*) base;
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp0_ = pumpkin_application_window_new ((GtkApplication*) self);
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	g_object_ref_sink (_tmp0_);
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_g_object_unref0 (self->window);
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	self->window = _tmp0_;
#line 12 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp1_ = self->window;
#line 12 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	gtk_window_present ((GtkWindow*) _tmp1_);
#line 102 "pumpkin-application.c"
}


static void pumpkin_application_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint) {
	PumpkinApplication * self;
	FILE* _tmp0_ = NULL;
#line 15 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	self = (PumpkinApplication*) base;
#line 15 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	g_return_if_fail (hint != NULL);
#line 16 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp0_ = stdout;
#line 16 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	fprintf (_tmp0_, "Open");
#line 117 "pumpkin-application.c"
}


static void pumpkin_application_class_init (PumpkinApplicationClass * klass) {
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	pumpkin_application_parent_class = g_type_class_peek_parent (klass);
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	((GApplicationClass *) klass)->activate = pumpkin_application_real_activate;
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	((GApplicationClass *) klass)->open = pumpkin_application_real_open;
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	G_OBJECT_CLASS (klass)->finalize = pumpkin_application_finalize;
#line 130 "pumpkin-application.c"
}


static void pumpkin_application_instance_init (PumpkinApplication * self) {
}


static void pumpkin_application_finalize (GObject* obj) {
	PumpkinApplication * self;
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PUMPKIN_TYPE_APPLICATION, PumpkinApplication);
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_g_object_unref0 (self->window);
#line 2 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	G_OBJECT_CLASS (pumpkin_application_parent_class)->finalize (obj);
#line 146 "pumpkin-application.c"
}


GType pumpkin_application_get_type (void) {
	static volatile gsize pumpkin_application_type_id__volatile = 0;
	if (g_once_init_enter (&pumpkin_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PumpkinApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pumpkin_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PumpkinApplication), 0, (GInstanceInitFunc) pumpkin_application_instance_init, NULL };
		GType pumpkin_application_type_id;
		pumpkin_application_type_id = g_type_register_static (gtk_application_get_type (), "PumpkinApplication", &g_define_type_info, 0);
		g_once_init_leave (&pumpkin_application_type_id__volatile, pumpkin_application_type_id);
	}
	return pumpkin_application_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	PumpkinApplication* application = NULL;
	PumpkinApplication* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 22 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp0_ = pumpkin_application_new ();
#line 22 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	application = _tmp0_;
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp1_ = args;
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp1__length1 = args_length1;
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_tmp2_ = g_application_run ((GApplication*) application, _tmp1__length1, _tmp1_);
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	result = _tmp2_;
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	_g_object_unref0 (application);
#line 23 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	return result;
#line 185 "pumpkin-application.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 21 "/home/dannote/Development/pumpkin/src/pumpkin-application.vala"
	return _vala_main (argv, argc);
#line 195 "pumpkin-application.c"
}



