/* pumpkin-application-window.c generated by valac 0.28.0, the Vala compiler
 * generated from pumpkin-application-window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <webkit2/webkit2.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>


#define PUMPKIN_TYPE_APPLICATION_WINDOW (pumpkin_application_window_get_type ())
#define PUMPKIN_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindow))
#define PUMPKIN_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindowClass))
#define PUMPKIN_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW))
#define PUMPKIN_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PUMPKIN_TYPE_APPLICATION_WINDOW))
#define PUMPKIN_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindowClass))

typedef struct _PumpkinApplicationWindow PumpkinApplicationWindow;
typedef struct _PumpkinApplicationWindowClass PumpkinApplicationWindowClass;
typedef struct _PumpkinApplicationWindowPrivate PumpkinApplicationWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define PUMPKIN_TYPE_TAB_LABEL (pumpkin_tab_label_get_type ())
#define PUMPKIN_TAB_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PUMPKIN_TYPE_TAB_LABEL, PumpkinTabLabel))
#define PUMPKIN_TAB_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PUMPKIN_TYPE_TAB_LABEL, PumpkinTabLabelClass))
#define PUMPKIN_IS_TAB_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PUMPKIN_TYPE_TAB_LABEL))
#define PUMPKIN_IS_TAB_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PUMPKIN_TYPE_TAB_LABEL))
#define PUMPKIN_TAB_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PUMPKIN_TYPE_TAB_LABEL, PumpkinTabLabelClass))

typedef struct _PumpkinTabLabel PumpkinTabLabel;
typedef struct _PumpkinTabLabelClass PumpkinTabLabelClass;
typedef struct _Block1Data Block1Data;
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))

struct _PumpkinApplicationWindow {
	GtkApplicationWindow parent_instance;
	PumpkinApplicationWindowPrivate * priv;
	GtkNotebook* notebook;
	GtkButton* new_tab_button;
	WebKitWebContext* web_context;
};

struct _PumpkinApplicationWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	PumpkinApplicationWindow* self;
	WebKitWebView* web_view;
	PumpkinTabLabel* label;
};


static gpointer pumpkin_application_window_parent_class = NULL;

GType pumpkin_application_window_get_type (void) G_GNUC_CONST;
enum  {
	PUMPKIN_APPLICATION_WINDOW_DUMMY_PROPERTY
};
PumpkinApplicationWindow* pumpkin_application_window_new (GtkApplication* application);
PumpkinApplicationWindow* pumpkin_application_window_construct (GType object_type, GtkApplication* application);
static void __lambda4_ (PumpkinApplicationWindow* self);
WebKitWebView* pumpkin_application_window_create_tab (PumpkinApplicationWindow* self);
static void ___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self);
GType pumpkin_tab_label_get_type (void) G_GNUC_CONST;
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
PumpkinTabLabel* pumpkin_tab_label_new (void);
PumpkinTabLabel* pumpkin_tab_label_construct (GType object_type);
static void __lambda6_ (Block1Data* _data1_);
#define PUMPKIN_ICON_SIZE 16
void pumpkin_tab_label_set_icon (PumpkinTabLabel* self, GdkPixbuf* pixbuf);
static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static GtkWidget* _pumpkin_application_window_create_tab_webkit_web_view_create (WebKitWebView* _sender, WebKitNavigationAction* navigation_action, gpointer self);
static void __lambda7_ (Block1Data* _data1_);
void pumpkin_tab_label_set_text (PumpkinTabLabel* self, const gchar* str);
static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda8_ (Block1Data* _data1_);
static void ___lambda8__pumpkin_tab_label_close (PumpkinTabLabel* _sender, gpointer self);
static void pumpkin_application_window_finalize (GObject* obj);


static void __lambda4_ (PumpkinApplicationWindow* self) {
	WebKitWebView* _tmp0_ = NULL;
	WebKitWebView* _tmp1_ = NULL;
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = pumpkin_application_window_create_tab (self);
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = _tmp0_;
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	webkit_web_view_load_uri (_tmp1_, "http://google.com");
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (_tmp1_);
#line 104 "pumpkin-application-window.c"
}


static void ___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	__lambda4_ ((PumpkinApplicationWindow*) self);
#line 111 "pumpkin-application-window.c"
}


PumpkinApplicationWindow* pumpkin_application_window_construct (GType object_type, GtkApplication* application) {
	PumpkinApplicationWindow * self = NULL;
	GtkApplication* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	WebKitWebContext* _tmp3_ = NULL;
	WebKitWebContext* _tmp4_ = NULL;
	WebKitWebView* web_view = NULL;
	WebKitWebView* _tmp5_ = NULL;
#line 10 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = application;
#line 11 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self = (PumpkinApplicationWindow*) g_object_new (object_type, "application", _tmp0_, NULL);
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = self->new_tab_button;
#line 13 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) ___lambda4__gtk_button_clicked, self, 0);
#line 14 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp2_ = self->new_tab_button;
#line 14 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_show ((GtkWidget*) _tmp2_);
#line 16 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp3_ = webkit_web_context_new ();
#line 16 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (self->web_context);
#line 16 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self->web_context = _tmp3_;
#line 17 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp4_ = self->web_context;
#line 17 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	webkit_web_context_set_favicon_database_directory (_tmp4_, NULL);
#line 19 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 21 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp5_ = pumpkin_application_window_create_tab (self);
#line 21 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	web_view = _tmp5_;
#line 22 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	webkit_web_view_load_uri (web_view, "http://google.com");
#line 10 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (web_view);
#line 10 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return self;
#line 160 "pumpkin-application-window.c"
}


PumpkinApplicationWindow* pumpkin_application_window_new (GtkApplication* application) {
#line 10 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return pumpkin_application_window_construct (PUMPKIN_TYPE_APPLICATION_WINDOW, application);
#line 167 "pumpkin-application-window.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return _data1_;
#line 176 "pumpkin-application-window.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 185 "pumpkin-application-window.c"
		PumpkinApplicationWindow* self;
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		self = _data1_->self;
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_g_object_unref0 (_data1_->label);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_g_object_unref0 (_data1_->web_view);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_g_object_unref0 (self);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		g_slice_free (Block1Data, _data1_);
#line 197 "pumpkin-application-window.c"
	}
}


static gpointer _cairo_surface_reference0 (gpointer self) {
#line 32 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return self ? cairo_surface_reference (self) : NULL;
#line 205 "pumpkin-application-window.c"
}


static void __lambda6_ (Block1Data* _data1_) {
	PumpkinApplicationWindow* self;
	void* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
#line 30 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self = _data1_->self;
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = webkit_web_view_get_favicon (_data1_->web_view);
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = _tmp0_;
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	if (_tmp1_ != NULL) {
#line 221 "pumpkin-application-window.c"
		cairo_surface_t* favicon = NULL;
		cairo_surface_t* _tmp2_ = NULL;
		cairo_surface_t* _tmp3_ = NULL;
		cairo_t* context = NULL;
		cairo_surface_t* _tmp4_ = NULL;
		cairo_t* _tmp5_ = NULL;
		gdouble width = 0.0;
		gdouble height = 0.0;
		cairo_t* _tmp6_ = NULL;
		gdouble _tmp7_ = 0.0;
		gdouble _tmp8_ = 0.0;
		GdkPixbuf* pixbuf = NULL;
		cairo_surface_t* _tmp9_ = NULL;
		gdouble _tmp10_ = 0.0;
		gdouble _tmp11_ = 0.0;
		GdkPixbuf* _tmp12_ = NULL;
		GdkPixbuf* _tmp13_ = NULL;
		GdkPixbuf* _tmp14_ = NULL;
		GdkPixbuf* _tmp15_ = NULL;
		GdkPixbuf* _tmp16_ = NULL;
		GdkPixbuf* _tmp17_ = NULL;
#line 32 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp2_ = webkit_web_view_get_favicon (_data1_->web_view);
#line 32 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp3_ = _cairo_surface_reference0 (_tmp2_);
#line 32 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		favicon = _tmp3_;
#line 33 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp4_ = favicon;
#line 33 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp5_ = cairo_create (_tmp4_);
#line 33 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		context = _tmp5_;
#line 35 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp6_ = context;
#line 35 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		cairo_clip_extents (_tmp6_, NULL, NULL, &_tmp7_, &_tmp8_);
#line 35 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		width = _tmp7_;
#line 35 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		height = _tmp8_;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp9_ = favicon;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp10_ = width;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp11_ = height;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp12_ = gdk_pixbuf_get_from_surface (_tmp9_, 0, 0, (gint) _tmp10_, (gint) _tmp11_);
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp13_ = _tmp12_;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp14_ = gdk_pixbuf_scale_simple (_tmp13_, PUMPKIN_ICON_SIZE, PUMPKIN_ICON_SIZE, GDK_INTERP_BILINEAR);
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp15_ = _tmp14_;
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_g_object_unref0 (_tmp13_);
#line 36 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		pixbuf = _tmp15_;
#line 38 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp16_ = pixbuf;
#line 38 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		gtk_window_set_icon ((GtkWindow*) self, _tmp16_);
#line 39 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_tmp17_ = pixbuf;
#line 39 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		pumpkin_tab_label_set_icon (_data1_->label, _tmp17_);
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_g_object_unref0 (pixbuf);
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_cairo_destroy0 (context);
#line 31 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
		_cairo_surface_destroy0 (favicon);
#line 295 "pumpkin-application-window.c"
	}
}


static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 30 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	__lambda6_ (self);
#line 303 "pumpkin-application-window.c"
}


static GtkWidget* _pumpkin_application_window_create_tab_webkit_web_view_create (WebKitWebView* _sender, WebKitNavigationAction* navigation_action, gpointer self) {
	GtkWidget* result;
	result = pumpkin_application_window_create_tab ((PumpkinApplicationWindow*) self);
#line 43 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return result;
#line 312 "pumpkin-application-window.c"
}


static void __lambda7_ (Block1Data* _data1_) {
	PumpkinApplicationWindow* self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 45 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self = _data1_->self;
#line 46 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = webkit_web_view_get_title (_data1_->web_view);
#line 46 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = _tmp0_;
#line 46 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp1_);
#line 47 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp2_ = webkit_web_view_get_title (_data1_->web_view);
#line 47 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp3_ = _tmp2_;
#line 47 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	pumpkin_tab_label_set_text (_data1_->label, _tmp3_);
#line 336 "pumpkin-application-window.c"
}


static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 45 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	__lambda7_ (self);
#line 343 "pumpkin-application-window.c"
}


static void __lambda8_ (Block1Data* _data1_) {
	PumpkinApplicationWindow* self;
	GtkNotebook* _tmp0_ = NULL;
	GtkNotebook* _tmp1_ = NULL;
	gint _tmp2_ = 0;
#line 53 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self = _data1_->self;
#line 54 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = self->notebook;
#line 54 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = self->notebook;
#line 54 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp2_ = gtk_notebook_page_num (_tmp1_, (GtkWidget*) _data1_->web_view);
#line 54 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_notebook_remove_page (_tmp0_, _tmp2_);
#line 55 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_destroy ((GtkWidget*) _data1_->label);
#line 56 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_destroy ((GtkWidget*) _data1_->web_view);
#line 366 "pumpkin-application-window.c"
}


static void ___lambda8__pumpkin_tab_label_close (PumpkinTabLabel* _sender, gpointer self) {
#line 53 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	__lambda8_ (self);
#line 373 "pumpkin-application-window.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return self ? g_object_ref (self) : NULL;
#line 380 "pumpkin-application-window.c"
}


WebKitWebView* pumpkin_application_window_create_tab (PumpkinApplicationWindow* self) {
	WebKitWebView* result = NULL;
	Block1Data* _data1_;
	WebKitWebContext* _tmp0_ = NULL;
	WebKitWebView* _tmp1_ = NULL;
	PumpkinTabLabel* _tmp2_ = NULL;
	GtkNotebook* _tmp3_ = NULL;
	GtkNotebook* _tmp4_ = NULL;
	GtkNotebook* _tmp5_ = NULL;
	GtkNotebook* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	WebKitWebView* _tmp8_ = NULL;
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_->_ref_count_ = 1;
#line 25 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_->self = g_object_ref (self);
#line 26 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp0_ = self->web_context;
#line 26 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp1_ = (WebKitWebView*) webkit_web_view_new_with_context (_tmp0_);
#line 26 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_object_ref_sink (_tmp1_);
#line 26 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_->web_view = _tmp1_;
#line 28 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp2_ = pumpkin_tab_label_new ();
#line 28 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_object_ref_sink (_tmp2_);
#line 28 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_->label = _tmp2_;
#line 30 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_signal_connect_data ((GObject*) _data1_->web_view, "notify::favicon", (GCallback) ___lambda6__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 43 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_signal_connect_object (_data1_->web_view, "create", (GCallback) _pumpkin_application_window_create_tab_webkit_web_view_create, self, 0);
#line 45 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_signal_connect_data ((GObject*) _data1_->web_view, "notify::title", (GCallback) ___lambda7__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 50 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp3_ = self->notebook;
#line 50 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_notebook_append_page (_tmp3_, (GtkWidget*) _data1_->web_view, (GtkWidget*) _data1_->label);
#line 51 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp4_ = self->notebook;
#line 51 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_notebook_set_tab_reorderable (_tmp4_, (GtkWidget*) _data1_->web_view, TRUE);
#line 53 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	g_signal_connect_data (_data1_->label, "close", (GCallback) ___lambda8__pumpkin_tab_label_close, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 59 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 61 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp5_ = self->notebook;
#line 61 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp6_ = self->notebook;
#line 61 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp7_ = gtk_notebook_page_num (_tmp6_, (GtkWidget*) _data1_->web_view);
#line 61 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_notebook_set_current_page (_tmp5_, _tmp7_);
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_tmp8_ = _g_object_ref0 (_data1_->web_view);
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	result = _tmp8_;
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	block1_data_unref (_data1_);
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_data1_ = NULL;
#line 63 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	return result;
#line 454 "pumpkin-application-window.c"
}


static void pumpkin_application_window_class_init (PumpkinApplicationWindowClass * klass) {
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	pumpkin_application_window_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	G_OBJECT_CLASS (klass)->finalize = pumpkin_application_window_finalize;
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/net/dannote/pumpkin/ui/window.ui");
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "notebook", FALSE, G_STRUCT_OFFSET (PumpkinApplicationWindow, notebook));
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "new_tab_button", FALSE, G_STRUCT_OFFSET (PumpkinApplicationWindow, new_tab_button));
#line 469 "pumpkin-application-window.c"
}


static void pumpkin_application_window_instance_init (PumpkinApplicationWindow * self) {
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 476 "pumpkin-application-window.c"
}


static void pumpkin_application_window_finalize (GObject* obj) {
	PumpkinApplicationWindow * self;
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PUMPKIN_TYPE_APPLICATION_WINDOW, PumpkinApplicationWindow);
#line 5 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (self->notebook);
#line 7 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (self->new_tab_button);
#line 8 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	_g_object_unref0 (self->web_context);
#line 3 "/home/dannote/Development/pumpkin/src/pumpkin-application-window.vala"
	G_OBJECT_CLASS (pumpkin_application_window_parent_class)->finalize (obj);
#line 492 "pumpkin-application-window.c"
}


GType pumpkin_application_window_get_type (void) {
	static volatile gsize pumpkin_application_window_type_id__volatile = 0;
	if (g_once_init_enter (&pumpkin_application_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PumpkinApplicationWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pumpkin_application_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PumpkinApplicationWindow), 0, (GInstanceInitFunc) pumpkin_application_window_instance_init, NULL };
		GType pumpkin_application_window_type_id;
		pumpkin_application_window_type_id = g_type_register_static (gtk_application_window_get_type (), "PumpkinApplicationWindow", &g_define_type_info, 0);
		g_once_init_leave (&pumpkin_application_window_type_id__volatile, pumpkin_application_window_type_id);
	}
	return pumpkin_application_window_type_id__volatile;
}



